export const endpoints = {
  login: '/login',
  forgot: '/forgot',
  reset: '/reset',
  users: '/users',
  flights: '/flights',
  flightSearch: '/flights/search',
  mapSearch: '/flights/search/map',
  departureCount: '/flights/search/count/departure',
  airlines: '/airlines',
  recommended: '/flights/recommended',
  book: '/book',
  flightUpdate: '/flightUpdate',
  bookHolidayPackage: '/bookHolidayPackage',
  bookings: '/bookings',
  createHolidayPackage: '/holidayPackages/holiday-packages',
  holidayPackages: '/holidayPackages',
  wishlist: '/wishlist',
  covid: '/admin/covid',
  getCanceled: '/admin/cancelled-flights',
  packageBookings: '/packageBookings'
};
