export const endpoints = {
  login: '/login',
  forgot: '/forgot',
  reset: '/reset',
  users: '/users',
  flights: '/flights',
  flightSearch: '/flights/search',
  flightById: '/flights/fetchById',
  mapSearch: '/flights/search/map',
  departureCount: '/flights/search/count/departure',
  airlines: '/airlines',
  recommended: '/flights/recommended',
  book: '/book',
  covidUpdate: '/covidUpdate',
  airlineUpdate: '/airlineUpdate',
  flightUpdate: '/flightUpdate',
  bookHolidayPackage: '/bookHolidayPackage',
  bookings: '/bookings',
  createHolidayPackage: '/holidayPackages/createHolidayPackage',
  holidayPackages: '/holidayPackages',
  wishlist: '/wishlist',
  getCovid: '/getCovid',
  getUsers: '/getUsers',
  getCanceled: '/getCanceledFlights',
  deleteCancel: '/deleteCancelFlight',
  deleteCovid: '/deleteCovidDestination',
  deleteSponsored: '/deleteSponsoredAirline',
};
