name: Build UI
on:
  push:
    branches: [develop]
    paths:
      - "flightpub-ui/**"
  pull_request:
    branches: [develop]
    paths:
      - "flightpub-ui/**"
jobs:
  build:
    env:
      CI: false
    name: check-ui
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install
        working-directory: ./flightpub-ui
      - name: Build
        run: yarn build
        working-directory: ./flightpub-ui
